### ISSUE TITLE
Invalid Cast Exception for Generics ?

### ISSUE THREAD

**Issue by Rextor** [Washi1337/AsmResolver#18] opened 2019-08-28 20:11 UTC
OldRod.Core.Recompiler.Transform :: TryInferVariableType
unable to casting generics from TypeSpecification to ByReferenceTypeSignature ?
![2019-08-29_004054](https://user-images.githubusercontent.com/23360895/63889163-b1e11700-c9f5-11e9-95cb-7ab345608f75.png)

**Comment by Washi1337** [comment] 2019-08-29 10:32
Thanks for the report. This seems not to be an issue of AsmResolver but from one of my projects that uses the library. Next time, please report to the appropriate repository for logistical purposes :)

Is there a possibility to get a sample of a binary in which this exception occurs?

**Comment by Washi1337** [comment] 2019-08-29 16:01
It seems the issue is related to the following issue:
https://github.com/Washi1337/OldRod/issues/6

Will close this one as it is not related to AsmResolver.

**Closed by Washi1337** 2019-08-29 16:01 UTC
Labels: bug
