### ISSUE TITLE
Some FieldDefinitiondoes Fullname

### ISSUE THREAD

**Issue by dashne** [Washi1337/AsmResolver#23] opened 2019-12-28 09:47 UTC
Hi, I recently used your library (AsmResolver) to resolve some of class member,but I dont know why for some of Field Definition I get Invalid Operation exception,it says it should be in readonly mode
while for others not, where i can change readonly property to true,because its getter is public not setter, is there any guide, please?

**Comment by Washi1337** [comment] 2019-12-28 10:02
Can you provide me a way to reproduce the issue (such as sample code and binary)?

**Comment by dashne** [comment] 2019-12-28 10:42
`var data = GetImage().Assembly.Modules[0].TopLevelTypes;
            var namespaces = new SortedDictionary<string, List<Tuple<string, TypeDefinition>>>();
            foreach (var typeDefinition in data)
            {
                if(typeDefinition.IsNested) continue;
                var str = typeDefinition.Namespace ?? "";
                if (!namespaces.ContainsKey(str))
                    namespaces.Add(str, new List<Tuple<string, TypeDefinition>>());
                namespaces[str].Add(new Tuple<string, TypeDefinition>(typeDefinition.Name, typeDefinition));
            }
            var comparator = new TypeDefComparator();
            foreach (var kv in namespaces)
            {
                kv.Value.Sort(comparator);
                var ns = new NamespaceNode(kv.Key, this, kv);
                Children.Add(ns);
            }`

GetImage() is Image ofnetDirectory's Header.
for binary,I just used TUP.AsmResolver.dll v1.0

**Comment by Washi1337** [comment] 2019-12-28 16:35
Version 1 is not supported anymore (as described in #22). Use AsmResolver 3 from master or 4 from v4 branch instead. 

In 3 you need to lock the metadata stream in order to access the high level representation of the .net binary. This is described on the wiki on github.

In 4 things are different, as it is a complete rewrite of the library. This will also be the actual version that will receive more updates in the future. It is a lot more documented (https://asmresolver.readthedocs.io/en/latest/) and is not as much of a PoC as earlier versions. It still has limited support for writing assemblies however.

**Comment by dashne** [comment] 2019-12-28 16:51
I'm currently using version 3, but used version 1 as testing assembly for resolving fields and types, I hope you can provide me, because I already did locking of assembly when I got Image of the header

**Comment by Washi1337** [comment] 2019-12-28 17:28
Ah my bad, I misread your reply. I thought you were using version 1 of the library.

I am, however, still unable to reproduce your issue, or I am misinterpreting your reply. If that's the case please forgive me. I tried the following code, which also includes enumerating the fields and printing their full names, but this does not seem to prompt any exceptions on my end:

```csharp
internal class TypeDefComparator : IComparer<Tuple<string, TypeDefinition>>
{
    public int Compare(Tuple<string, TypeDefinition> x, Tuple<string, TypeDefinition> y)
    {
        return string.Compare(x.Item1, y.Item1, StringComparison.Ordinal);
    }
}

internal class Program
{
    public static void Main(string[] args)
    {
        var assembly = WindowsAssembly.FromFile(@"D:\Washi\Desktop\TUP.AsmResolver.dll");
        
        var data = assembly.NetDirectory.MetadataHeader.LockMetadata().Assembly.Modules[0].TopLevelTypes;
        var namespaces = new SortedDictionary<string, List<Tuple<string, TypeDefinition>>>();
        foreach (var typeDefinition in data)
        {
            if (typeDefinition.IsNested) continue;
            var str = typeDefinition.Namespace ?? "";
            if (!namespaces.ContainsKey(str)) namespaces.Add(str, new List<Tuple<string, TypeDefinition>>());
            namespaces[str].Add(new Tuple<string, TypeDefinition>(typeDefinition.Name, typeDefinition));
        }

        var comparator = new TypeDefComparator();
        foreach (var kv in namespaces)
        {
            kv.Value.Sort(comparator);
            foreach (var node in kv.Value)
            {
                foreach (var field in node.Item2.Fields)
                    Console.WriteLine(field);
            }
        }
    }
}
```

I am not sure what these `NamespaceNode` instances really do, nor do I know exactly what your implementation is for `TypeDefComparator`, so I replaced them with simple `Console.WriteLine` calls and a simple implementation of the `IComparer<T>` interface. Can you try finding another, possibly smaller and/or more focused on the issue?

**Comment by dashne** [comment] 2019-12-29 11:19
Thank you for your reply,I Get Image For Assembly Node when loaded and call LoadMetaData and then UnloadMetaData , When I click On each individual  Type member in tree nodes , I'm just use the Image to resolve type Definition with its hierarchy as you know better than me,But it give me that strange behavior on Some Fields , is that because I dont lock metadata when I populate the data on selection change? and your code is OK because all types and fields get loaded at once, should I use lockmetadata() every time to populate  type members?
I hope you understand me.
my second question is that, is v4 able to write mixed code assembly?

**Comment by Washi1337** [comment] 2019-12-29 11:53
The idea behind locking metadata is to allow for a high-level interpretation of the current state of the metadata streams that is **thread-safe**. The streams are still accessible, they are just in a read-only mode (you could compare it to a read-only snapshot). As a result, while in high-level mode, you can only change properties from high-level models (`TypeDefinition`, `MethodDefinition` etc.). Trying to change properties from raw metadata structures (`TableStream`, `MetadataTable`, `MetadataRow` etc.) will result in an `InvalidOperationException` (e.g. see [here](https://github.com/Washi1337/AsmResolver/blob/dfb7698d78c5cf7764331a9546fc0b8c154edc81/AsmResolver/Net/Metadata/MetadataTable.cs#L241) and [here](https://github.com/Washi1337/AsmResolver/blob/fe91ae01e583bc624f914f5815860fb9905a6b19/AsmResolver/Net/Cts/IMetadataMember.cs#L69)).

Unlocking metadata will enable writing again, but also does more. It commits every change that you made through the high-level representation by completely rebuilding the streams (Side note: for this reason, unlocking can be an expensive task). Once it is unlocked, the metadata image is invalidated.

Furthermore, `LockMetadata()` can only be called once. If you want to lock again, you first need to unlock again. Calling the lock metadata method a second time before it was unlocked results in an `InvalidOperationException` (see [here](https://github.com/Washi1337/AsmResolver/blob/master/AsmResolver/Net/MetadataHeader.cs#L181)). Similarly, calling `UnlockMetadata` before locking first will result in a similar exception.

Maybe one of these `InvalidOperationException`s is where the issue is at for you?

Generally, what you want to do is **avoid** locking and unlocking as much as possible. It seems you are trying to make some kind of .NET assembly explorer/inspector. In this case it is probably enough to acquire the image **only once** by locking the metadata once you have loaded the assembly, and only unlock upon saving the binary or when you need write access again to the raw structures.

About writing native images using AsmResolver 4, yes this is possible in the lowest level mode. It is not yet supported in higher level mode, but this is planned, along with other options that relate to the preservation of the structure (tokens, indices etc) of the metadata.

**Comment by dashne** [comment] 2019-12-29 19:56
Yes, You're right , but from your example, if you unlockMetaData before Going through data population, and then go through data population, you get InvalidOperationExceptions , the strange is that for some types I get this exception, and for some not, anyway I have to lockmetaData when populating, and then unlockMetaData when I finished loading type members.
Thanks.

**Comment by Washi1337** [comment] 2019-12-29 20:49
Yes unlocking metadata before you use the higher level models can lead to `InvalidOperationException`s. 

Does that mean you have solved your issue?

**Comment by dashne** [comment] 2019-12-30 13:44
Yes, but it is time consuming.
Please be Patient with me.
 could you show an example in low level doing the same typeDefinition, methodDefinition, ..etc population as previous example.
Thanks.

**Comment by Washi1337** [comment] 2019-12-30 14:27
No worries, there is no pressure.

Working in low level mode requires lots more manual work, like resolving the names of the types yourself, as well as parsing member signatures etc. For the format of the .NET metadata, I'll refer you to the [ECMA-335](https://www.ecma-international.org/publications/standards/Ecma-335.htm), which describes exactly the layout of all tables, rows, columns, blob signatures and the like.

Easiest way would be to obtain for example the types in a .NET image using AsmRes 3, would be by grabbing the tables stream instance, together with the strings and blob streams from the metadata header, and then go over all rows in the TypeDefinition table:

```csharp
var tableStream = metadataHeader.GetStream<TableStream>();
var stringStream = metadataHeader.GetStream<StringStream>();

var table = tableStream.GetTable<TypeDefinitionTable>();
foreach (var row in table)
{
    // Resolve name and namespace.
    string name = stringStream.GetStringByOffset(row.Column2);
    string ns = stringStream.GetStringByOffset(row.Column3);
    // ...
}
```

Finding out which of them are top-level types, and which are nested types, can be done by going over the nested class table. Obtaining fields and methods can be done in a similar fashion as well. Be sure to check the `FieldList` (Column5) and `MethodList` (Column6) columns in the TypeDef table to figure out the declaring type of each field and method.

Note: In AsmRes 4, this procedure is simplified with better definitions of each metadata row, as well as dedicated methods that obtain e.g. the methods and fields of a type by its metadata token. This is also described on the [wiki](https://asmresolver.readthedocs.io/en/latest/peimage/dotnet.html#tables-stream).

**Comment by dashne** [comment] 2019-12-30 17:23
Is there lockMetaData in AsmRes 4, I don't see any!

**Comment by Washi1337** [comment] 2019-12-30 19:42
The design of AsmResolver 4 is not finalized yet, but has shortcuts that hide the locking/unlocking mechanism, and should be easier to use:

https://asmresolver.readthedocs.io/en/latest/dotnet/basics.html#opening-a-net-module

The documentation is therefore also not as thorough yet for this part.

**Comment by dashne** [comment] 2019-12-30 19:52
I hope the AsmResolver 4 and its Documentation be finished soon and completely.
I'll wait, because I like to start with the last Version.
Thanks

**Closed** 2019-12-30 22:06 UTC
