### ISSUE TITLE
Don't precompute (or allow disabling of) diagnostic prefix for CilAssembler

### ISSUE THREAD

**Issue by SamboyCoding** [Washi1337/AsmResolver#260] opened 2022-03-04 17:35 UTC
## Problem Description
I'm currently in the process of switching to AsmResolver from Cecil for generating managed assemblies, and I've found that AsmResolver is quite a bit slower than Cecil when it comes to saving assemblies (among other things, but this is what I'm investigating right now). 

Having now run it through a profiler (specifically dotTrace), I've found that approximately 12.5% of the total time to save assemblies is coming from the call to SafeToString in CilMethodBodySerializer#BuildRawCodeStream, the result of which is only used as the diagnostic prefix for CilAssembler should something go drastically wrong (which it hasn't yet, in my experimentation). 

Being able to disable this (or even better, compute it only if an error actually occurs) would be nice for applications where speed is preferable to easily reproducible log output - if need be, an option can be provided by the parent application to re-enable the logging for better error messages.

## Proposal
The addition of a feature flag/configuration option to disable certain calls such as this one which are only for ease of diagnostic output

## Alternatives
A better (i.e. more convenient from a developer point of view) however more complex to implement alternative would be the ability for certain time-intensive computations like this to be done as-needed instead of ahead of time.

## Additional context
N/A

**Comment by Washi1337** [comment] 2022-03-04 23:51
Good catch. Thanks for finding the hotspot.

Initial testing shows that using a constructor taking a delegate for lazy loading the diagnostic prefix instead of pre-computing it is already quite a good option (See #261). I am therefore more inclined to go with this option rather than adding yet another builder setting / flag and thus adding more complexity to the API. 

Could you maybe verify that you can see similar improvements in performance with this change?

**Comment by SamboyCoding** [comment] 2022-03-05 00:49
Hey, thanks for getting this implemented so fast! Yes I can confirm the linked PR removes the hotspot.

However, while we're at it, do you have any idea why invoking ModuleDefinition#ToPEImage is no faster on multiple threads (in fact it's actually slower in my tests) than it is in serial (even with a unique instance of ManagedPeImageBuilder per assembly)? Is there some sort of lock contention going on?

Is there anywhere you can be reached for a more direct conversation? I have the feeling I'll be having plenty of questions about AsmResolver in the coming weeks/months haha.

**Comment by SamboyCoding** [comment] 2022-03-05 01:29
Also, is there any possibility of getting a dedicated net6 build? That way we benefit from the optimized string interpolation handler, among other things.

**Comment by Washi1337** [comment] 2022-03-05 11:11
> However, while we're at it, do you have any idea why invoking ModuleDefinition#ToPEImage on multiple threads is no faster on a collection of assemblies (in fact it's actually slower in my tests) than it is in serial (even with a unique instance of ManagedPeImageBuilder per assembly)? Is there some sort of lock contention going on?

These types of bottlenecks are always hard to pinpoint, and would often need some kind of insight on the modules that you're trying to process. The place where AsmResolver uses locks is in the `LazyVariable` class, which is used throughout the entire solution to lazily initialize mutable variables / fields. Locks are used here to guarantee thread-safety throughout the initialization of the variable, but they are isolated on a per-field basis, and never shared across other instances of `LazyVariable` or other modules. I don't see a direct reason yet that processing multiple modules at the same time would  have a big impact in that regards. But it is hard to say without reproducible / measurable tests.

One idea that comes to mind with your case though, is that in many cases AsmResolver takes a long time processing things because it is resolving references to external assemblies, types and/or members. This is further amplified when you have a collection of assemblies. While all default implementations of `IAssemblyResolver` cache instances of the resolved assemblies, AsmResolver by default does _not_ share these instances across `ModuleDefinition`s. If two assemblies within your collection reference the same library (e.g. `System.Private.CoreLib`), then this reference may therefore be resolved _twice_. This means that two separate instances of `AssemblyDefinition` (which all need to be lazily initialized for reading its contents) will be used. You may want to consider sharing the same `IAssemblyResolver` instance across all of your modules, and see if it improves anything.

Side note, this is one of the things (among many other things) that the [workspaces feature branch](/Washi1337/AsmResolver/tree/feature/workspaces) attempts to address. Fair warning though: This branch is very experimental, still lacks documentation greatly, and breaking API changes may happen at any time.

> Is there anywhere you can be reached for a more direct conversation (e.g. discord, gitter)? I have the feeling I'll be having plenty of questions about AsmResolver in the coming weeks/months haha.

Seems like there is some demand for some kind of chat platform yes. I will look into creating some kind of Discord server or similar, as others may also have quick questions they want answers to. Providing a platform where users can help each other seems like something we can maybe give a try.

> Also, is there any possibility of getting a dedicated net6 build? That way we benefit from the optimized string interpolation handler, among other things.

I have been asked this before as well. I haven't really had the time (yet) to look into how much it would actually benefit. However,  was not aware of the fact though that targeting newer .NET versions can also affect how the code is compiled. If this is the case, then it is definitely worth exploring then, maybe with some benchmark tests.

**Comment by SamboyCoding** [comment] 2022-03-05 13:36
> These types of bottlenecks are always hard to pinpoint, and would often need some kind of insight on the modules that you're trying to process.

Well, this is the complicated part. The project in question is called [Cpp2IL](https://github.com/SamboyCoding/Cpp2IL) and essentially I'm generating approximately 60 assemblies, including mscorlib assemblies, from almost-scratch (in so far as there were no managed assemblies before the application ran, but I do have information on what I need to create and in which assemblies). AsmResolver is already much better in this regard than Cecil as it allows me to manually specify a corlib assembly when creating other assemblies, and import types from that with the correct primitive type IDs (e.g. in custom attributes), without me manually reflecting to change a private field on the type definitions.

So at least one of the assemblies I'm saving is identical in structure to mscorlib from (unity's fork of the mono version of) .NET framework 4.5, but the main difference is that, at least in this stage of my integration with AsmResolver (this will change down the line!) all of the methods have very minimal method bodies (consisting of 1-4 CIL instructions, and at most 1 local) to ensure they can be loaded in a decompiler and appear empty or with a default return statement, and nothing more.

The benchmark I collected was specifically run on VRChat which is unusual in that they use Beebyte Obfuscator, which creates dozens of "fake" types and methods, significantly inflating the binary size, and unique in that it has a truly obscene codebase regardless, resulting in the "empty" stub assembly being over 10MB in size, without any meaningful method bodies. Compare this to the ~900kb size of a stub mscorlib.

For a bit more of a concrete idea of the scale here, I'm generating and outputting 136 assemblies containing 19,553 types, 87,874 fields, and 231,481 methods. So it's not surprising to me that this process (the actual generation and saving) takes about 15 seconds, of which 4-6 seconds is spent writing assemblies.

**Comment by Washi1337** [comment] 2022-03-08 20:38
See #265 for discussion on .NET 6 targets and implications.

**Comment by Washi1337** [comment] 2022-03-11 12:33
Implemented in 4.9.0

**Closed by Washi1337** 2022-03-11 12:33 UTC
Labels: enhancement, dotnet, performance

**Comment by Washi1337** [comment] 2022-03-11 12:35
> For a bit more of a concrete idea of the scale here, I'm generating and outputting 136 assemblies containing 19,553 types, 87,874 fields, and 231,481 methods. So it's not surprising to me that this process (the actual generation and saving) takes about 15 seconds, of which 4-6 seconds is spent writing assemblies.

This is quite the stress test. I don't think I have put AsmResolver on such a heavy workload yet myself all at once.

.NET 6.0 targets have been pushed to nuget. If your problem still persists, it probably warrants a separate issue though, in which we can explore further where this bottleneck may happen.
