### ISSUE TITLE
`SignatureComparer` Asymmetry

### ISSUE THREAD

**Issue by ds5678** [Washi1337/AsmResolver#594] opened 2024-11-17 18:32 UTC
### AsmResolver Version

6, beta 1

### .NET Version

.NET 8

### Operating System

Windows

### Describe the Bug

`Equals(IMethodDescriptor? x, IMethodDescriptor? y)` can return different values depending on the order of x and y.

### How To Reproduce

I encountered this when resolving `IMethodDescriptor` instances and comparing them to their resolved `MethodDefinition`. If y is the resolved method, everything works as expected. If x is the resolved method, inaccuracies can occur.

### Expected Behavior

All methods in `SignatureComparer` should be symmetric.

### Actual Behavior

`Equals(IMethodDescriptor? x, IMethodDescriptor? y)` can return different values depending on the order of x and y.

### Additional Context

Other `Equals` methods appear to have the same code pattern that led to this bug.

**Comment by Washi1337** [comment] 2024-11-18 20:24
Do you have some concrete examples of this?

Note that resolving `MethodSpecification` results in a `MethodDefinition`, which strips off all generic instantiations. This is by design.

**Comment by ds5678** [comment] 2024-11-21 17:59
> Do you have some concrete examples of this?

I wrote a unit test to demonstrate.

**Closed** 2024-11-25 20:49 UTC
Labels: bug
